version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: doud-ems-zennotes-server-1
      APP_PORT: 7878

  server:
    image: adibhanna/zennotes:latest
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    environment:
      ZENNOTES_AUTH_TOKEN: "${APP_SEED}"
      ZENNOTES_BROWSE_ROOTS: "/workspace"
    volumes:
      - ${APP_DATA_DIR}/data/workspace:/workspace
      - ${APP_DATA_DIR}/data/server:/data
